# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver-db
    hostname: db
    ports:
      - "${SQLSERVER_PORT:-1433}:1433"
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - MSSQL_SERVER=${MSSQL_SERVER}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - MSSQL_USERNAME=${MSSQL_USERNAME}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - TABLE_NAME=${TABLE_NAME}
      - MSSQL_CONNECTION_STRING=${MSSQL_CONNECTION_STRING}
    # volumes:
    #   - sqlserverdata:/var/opt/mssql
    healthcheck:
        test: >
          CMD-SHELL /opt/mssql-tools18/bin/sqlcmd -No -S localhost -U sa -P "$${MSSQL_SA_PASSWORD}" -Q "SELECT 1"
        interval: 30s
        retries: 3
        start_period: 30s
        timeout: 10s

# volumes:
#   sqlserverdata:
